---
title: "2018_TOC_Data"
author: "KentoLogan"
date: "11/3/2020"
output: github_document
---

#LOAD LIBRARIES
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```

#LOAD DATA
```{r}
excel_sheets("~/GitHub_Files/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx")
metadata<- read_excel("~/GitHub_Files/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Metadata")
data<- read_excel("~/GitHub_Files/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Data")
```

#PREP DATA
```{r}
joined<- left_join(metadata, data)

toc<- joined %>% 
  mutate(Datetime= ymd_hm(Datetime)) %>% 
  group_by(Experiment, Bottle) %>% 
  mutate(interv= interval(first(Datetime), Datetime),
         hours= interv/3600,
         days= hours/24) %>% 
  ungroup() %>% 
  select(Bottle:Datetime, hours, days, everything(), -interv)
```
#PLOT THE CURVES
##Pivot!!!!
```{r}
pivot_toc<- toc %>% 
  select(Location,Bottle,Treatment,days,TOC,PTOC) %>% 
  pivot_longer(TOC:PTOC, names_to= "sample", values_to= "value")

pivot_toc_sd<- toc %>% 
  select(Location,Bottle,Treatment,days,TOC_sd,PTOC_sd) %>% 
  pivot_longer(TOC_sd:PTOC_sd, names_to= "sample", names_prefix= "sd_", values_to= "sd")

pivot_join<- left_join(pivot_toc, pivot_toc_sd) %>% 
  mutate(sample= ifelse(sample=="TOC", "Bottle", "Vial"))
```
##Plot
```{r fig.height=6, fig.width=8}
custom.colors<- c("Control"="#377EB8", "Ash Leachate"="#4DAF4A", "Mud Leachate"="#E41A1C", "Glucose_Nitrate_Phosphate"="#FF7F00", "Vial"="#377EB8", "Bottle"="#E41A1C")
levels<- c("Control", "Ash Leachate", "Mud Leachate", "Glucose_Nitrate_Phosphate", "Bottle", "Vial")

pivot_join %>% 
  drop_na(value) %>% 
  mutate(Treatment= factor(Treatment, levels = levels),
         sample= factor(sample, levels = levels)) %>% 
  ggplot(aes(x= days, y=value, group= interaction(Treatment, Bottle)))+
  geom_errorbar(aes(ymin= value - sd, ymax= value + sd, color=sample), width=0.4)+
  geom_point(aes(fill= sample), size= 3, shape= 21, alpha= 0.7)+
  scale_color_manual(values= custom.colors)+
  scale_fill_manual(values = custom.colors)+
  labs(x= "Days", y= expression("Total Organic Carbon, micromol C L"^-1), color= "", fill= "")+
  theme_bw()+
  facet_grid(rows = "Treatment")+
  guides(color = F)
```
THE ANALYTICAL DETECTION LIMIT FOR OUR TOC ANALYSIS IS ~1.5 MICROMOL C L^-1.

##TOC v PTOC: Bottle Samp. v Vial Samp.
```{r}
library(lmodel2)

reg.data<- toc %>% 
  drop_na(TOC) %>% 
  filter(Timepoint> 0)

reg<- lmodel2(PTOC~TOC,data= reg.data,nperm=99)
```

##Regression Results
```{r}
reg
```
```{r}
intercept<- reg$regression.results[3,2]
slope<- reg$regression.results[3,3]

two.int<- reg$confidence.intervals[3,2]
two_slope<- reg$confidence.intervals[3,4]
nine.int<- reg$confidence.intervals[3,3]
nine_slope<- reg$confidence.intervals[3,5]
```

```{r}
reg.data %>%
  ggplot(aes(x= TOC, y= PTOC))+
  geom_errorbar(aes(ymin= PTOC-PTOC_sd, ymax= PTOC+PTOC_sd), width= 0.05)+
  geom_errorbarh(aes(xmin= TOC-TOC_sd, xmax= TOC+TOC_sd), width= 0.05)+
  geom_point(shape= 21, size= 4, alpha= 0.7)+
  geom_abline(intercept= intercept, slope= slope, color= "black", linetype= 2, size= 1)+
  geom_abline(intercept = two.int, slope = two_slope, color= "black", linetype=3, size= 1)+
  geom_abline(intercept = nine.int, slope = nine_slope, color= "black", linetype=3, size= 1)+
  labs(x= expression("Bottle TOC, micromol C L"^-1), y= expression("Vial TOC, micromol C L"^-1))+
  theme_bw()+
  annotate(geom= "text", label= expression(atop("y = 1.03x - 2.12", paste("r"^2, "= 0.88", italic("  p="), "0.01"))),x= 80, y=88, size=4)
```
```{r}
bc<- read_rds("~/GitHub_Files/144l_students/Output_Data/2018_Processed_Bact_Abund_OFFICIAL.rds")

merge<- left_join(toc, bc) %>% 
  select(Experiment:days, TOC:PTOC_sd, cells:diff_ln_cells, bc, ave_bc, sd_bc, everything()) %>% 
  group_by(Treatment, Bottle) %>% 
  fill(exp_start:sd_lag) %>% 
  ungroup()

subsetII<- merge %>% 
  select(Experiment: days, PTOC, bc)
```

#INTERPOLATE DATA
```{r}
library(zoo)
library(dplyr)
library(plyr)
```

##Split
```{r}
to_interpolate<- merge %>%
  select(Bottle, Timepoint, days, PTOC, bc) %>% 
  group_by(Bottle)

list<- to_interpolate %>% 
  group_split()

keys<- to_interpolate %>% 
  group_keys() %>% 
  mutate(key= paste(Bottle))

names(list)<- keys$key
```

##Function
```{r}
interp.funct<- function(x){
  y<- zoo(x, order.by = x$days)
  interp_toc<- round(as.numeric(na.approx(y$PTOC, na.rm = F)), 1)
  interp_bc<- round(as.numeric(na.approx(y$bc, na.rm = F)), 1)
  z<- cbind(y, interp_toc, interp_bc)
  as_tibble(z)
}
```

##Apply & Combine
```{r}

interpolated<- lapply(list, interp.funct) %>% 
   plyr::ldply(., as.data.frame)%>% 
  select(-c(.id, PTOC, bc, days)) %>% 
  mutate_at(vars(Timepoint: interp_bc), as.numeric) %>%
  left_join(merge, .)
  
```

##Estimate DOC, Bioavailability, and BGE
```{r}
doc<- interpolated %>% 
  mutate(doc= interp_toc - interp_bc)%>% 
  group_by(Bottle)%>% 
 mutate(bioav_doc= (first(doc)- last(na.omit(doc)))/ first(doc),
         doc_exp_end= ifelse(Timepoint== exp_end, doc, NA),
         delta_doc= first(doc)- doc_exp_end,
         tdelta_doc= first(doc)- last(na.omit(doc)),
         bge= ifelse(delta_doc> 1.5, delta_bc/delta_doc, NA)) %>% 
  fill(doc_exp_end:bge, .direction = "downup") %>% 
  ungroup()

subsetIII<- doc %>% 
  select(Bottle, Timepoint, exp_end, days, interp_toc, doc, bioav_doc, doc_exp_end, delta_bc, delta_doc, tdelta_doc, bge)
```

##Treatment Averages
```{r}
averages<- doc %>% 
  group_by(Treatment, Timepoint) %>% 
  mutate(ave_toc= mean(PTOC),
         TOC_sd= sd(PTOC)) %>% 
  ungroup() %>% 
  group_by(Treatment) %>% 
  mutate(ave_bioav_doc= mean(bioav_doc),
         sd_bioav_doc= sd(bioav_doc),
         ave_delta_doc= mean(delta_doc),
         sd_delta_doc= sd(delta_doc),
         ave_tdelta_doc= mean(tdelta_doc),
         sd_tdelta_doc= sd(tdelta_doc),
         ave_bge= mean(bge),
         sd_bge= sd(bge)) %>% 
  ungroup()
```

##Plot Treatment Curves
```{r fig.height=4, fig.width=6}
averages %>% 
  mutate(Treatment= factor(Treatment, levels = levels)) %>% 
  drop_na(ave_toc) %>% 
  ggplot(aes(x= days, y= ave_toc, group= interaction(Treatment)))+
  geom_errorbar(aes(ymin= ave_toc - TOC_sd, ymax= ave_toc+ TOC_sd, color= Treatment), width= 0.4)+ 
  geom_point(aes(fill=Treatment), size= 3, shape=21, alpha= 0.7)+
  geom_line(aes(color=Treatment), size= 1, alpha= 0.7)+
  scale_color_manual(values = custom.colors)+
  scale_fill_manual(values = custom.colors)+
  labs(x= "Days", y= expression("Total Organic Carbon, micromols C L"^-1), color= "", fill= "")+
  theme_bw()+
  guides(color= F)
```
##Plot Treatment Averages
```{r}
bar.data<- averages %>% 
  select(Treatment, ave_bioav_doc:sd_bge) %>% 
  distinct()
  
```
```{r fig.height=6}
bioav<- bar.data %>% 
  ggplot(aes(x= factor(Treatment, levels = levels), 
             y= ave_bioav_doc, group= interaction(Treatment)))+
  geom_col(color= "black", fill= "white", alpha=1)+
  geom_errorbar(aes(ymin= ave_bioav_doc- sd_bioav_doc, ymax= ave_bioav_doc+ sd_bioav_doc), width=0.1, size= 0.5)+
  labs(x= "", y= expression(paste("Bioavailable DOC Fraction")),
color= "")+
  theme_bw()+
  guides(fill=F)
```
```{r fig.height=6}
deldoc<- bar.data %>% 
  ggplot(aes(x= factor(Treatment, levels = levels), 
             y= ave_delta_doc, group= interaction(Treatment)))+
  geom_col(color= "black", fill= "white", alpha=1)+
  geom_errorbar(aes(ymin= ave_delta_doc- sd_delta_doc, ymax= ave_delta_doc+ sd_delta_doc), width=0.1, size= 0.5)+
  labs(x= "", y= expression(paste("Delta DOC (to stationary), micromol C L"^-1)),
color= "")+
  theme_bw()+
  guides(fill=F)
```
```{r fig.height=6}
total_deldoc<- bar.data %>% 
  ggplot(aes(x= factor(Treatment, levels = levels), 
             y= ave_tdelta_doc, group= interaction(Treatment)))+
  geom_col(color= "black", fill= "white", alpha=1)+
  geom_errorbar(aes(ymin= ave_tdelta_doc- sd_tdelta_doc, ymax= ave_tdelta_doc+ sd_tdelta_doc), width=0.1, size= 0.5)+
  labs(x= "", y= expression(paste("Delta DOC (total), micromol C L"^-1)),
color= "")+
  theme_bw()+
  guides(fill=F)
```
```{r fig.height=6}
bge<- bar.data %>% 
  ggplot(aes(x= factor(Treatment, levels = levels), 
             y= ave_bge, group= interaction(Treatment)))+
  geom_col(color= "black", fill= "white", alpha=1)+
  geom_errorbar(aes(ymin= ave_bge- sd_bge, ymax= ave_bge+ sd_bge), 
                width=0.1, size= 0.5)+
  labs(x= "", y= expression(paste("Bacterial Growth Efficiency")),
color= "")+
  theme_bw()+
  guides(fill=F)
```

```{r}
library(patchwork)
```
```{r fig.height=8}
deldoc/total_deldoc/total_deldoc/bge+ plot_annotation(title = "2018 Processed DOC&BGE", tag_levels = "a")
```
```{r}
saveRDS(averages,"~/GitHub_Files/144l_students/Output_Data/DOC_BGE.rds")
```

